import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const runCommand = promisify(exec);

const projectName = process.argv[2] || 'myWebProject';

const srcFolderName = path.join(projectName, 'src');
const serverFile = path.join(projectName, 'server.js');

async function setupProject() {
    try {
        await mkdir(srcFolderName, { recursive: true });

        console.log(`Created project folder: ${projectName}`);

        const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <h1>Welcome to ${projectName}</h1>

    <script src="main.js"></script>
</body>
</html>`;

        await writeFile(
            path.join(srcFolderName, 'index.html'),
            htmlContent
        );

        console.log('Created: src/index.html');

        const cssContent = `body {
    font-family: Arial, sans-serif;
    text-align: center;
    margin-top: 50px;
}

h1 {
    color: royalblue;
}`;

        await writeFile(
            path.join(srcFolderName, 'style.css'),
            cssContent
        );

        console.log('Created: src/style.css');

        const jsContent = `console.log("${projectName} is ready!");`;

        await writeFile(
            path.join(srcFolderName, 'main.js'),
            jsContent
        );

        console.log('Created: src/main.js');

        const serverContent = `import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const app = express();
const PORT = 3000;

app.use(express.static(path.join(__dirname, 'src')));

app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'src', 'index.html'));
});

app.listen(PORT, () => {
    console.log(\`Server running on http://localhost:\${PORT}\`);
});
`;

        await writeFile(serverFile, serverContent);

        console.log('Created: server.js');

        const packageJson = {
            name: projectName.toLowerCase(),
            version: '1.0.0',
            description: 'Generated by Project Setup Tool',
            main: 'server.js',
            type: 'module',
            scripts: {
                start: 'node server.js'
            },
            dependencies: {
                express: '^5.1.0'
            }
        };

        await writeFile(
            path.join(projectName, 'package.json'),
            JSON.stringify(packageJson, null, 2)
        );

        console.log('Created: package.json');

        const gitignoreContent = `node_modules/
.env
dist/
`;

        await writeFile(
            path.join(projectName, '.gitignore'),
            gitignoreContent
        );

        console.log('Created: .gitignore');

        console.log('\nInstalling dependencies...\n');

        await runCommand('npm install', {
            cwd: projectName
        });

        console.log('Dependencies installed successfully.');

        console.log('\nProject setup completed!');
        console.log('\nTo start the project:\n');
        console.log(`cd ${projectName}`);
        console.log('npm start');
    } catch (error) {
        console.error('Error:', error.message);
    }
}

setupProject();